### ISSUE TITLE
Improved set of default gptmd mods

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1046]
Determine which mods have truly high probablity and uncheck boxes for low probabilty mods.

**Comment by trishorts** [comment]
get rid of off target carbamidomethylation by default

**Comment by rmillikin** [comment]
revamped a bit in #1512 . 
I recategorized PTMs into:
```
Common Biological
Common Artifact
Less Common
Metals
Speculative
```

Everything except speculative is checked by default for GPTMD. But it's easier to separate out the less common things from the common ones, so you can just uncheck the `Less Common` category instead of trying to pick out the things we generally think are less likely from the likely.

**Comment by rmillikin** [comment]
We could also add a `Rare` category
