### ISSUE TITLE
GPTMD needs max mods per peptide field

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1049]

**Comment by rmillikin** [comment]
This seems like a straightforward thing but I'll just add a comment that "Max mods per peptide" is how many mods to *search* with. It doesn't define how many mods are *annotated* in the database. This distinction is obvious in the search and calibration tasks because PTMs aren't being annotated. But in the GPTMD window it's likely not clear. I'm not sure if a tooltip is enough to inform the user of this very important difference. Something to think about
