### ISSUE TITLE
[PeptideTermMod:Lysine not cleaved at N-term]

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1097]
This seems like a trypsin-specific modification. Should we uncheck it when searching other enzymes? It's popping up in nonspecific searches...

**Comment by rmillikin** [comment]
Maybe we should have protease-specific mods?

**Comment by zrolfs** [comment]
Why is this even a thing? Does anybody know?

**Comment by trishorts** [comment]
GG is  a protease specific mod that occurs upon cleaveage of ubiquitin side chains. There are others, and these tags change with other proteases.

**Comment by zrolfs** [comment]
So lysine not being cleaved is indicative of ubiquitin? I am confused. Isn't this just a missed cleavage that happens to be on the N-terminus?

**Comment by trishorts** [comment]
No lysine still gets cleaved but there is an addition two amino acid tag hanging off the side

**Comment by trishorts** [comment]
![image](https://user-images.githubusercontent.com/16841846/41316067-eb03324e-6e56-11e8-89c4-22c9b5382cc6.png)

**Comment by zrolfs** [comment]
I'm getting it for nonspecific searches where 
"[PeptideTermMod:Lysine not cleaved at N-term]LWGKQKNK"
has the same mass as
"KLWGKQKNK"
so there doesn't appear to be a GG?

**Comment by trishorts** [comment]
I don't know what that is. I was talking about protease specific mods. I don't think there should be any for non-specific. 
The notation you write looks like a uniprot mod. check uniprot ptmlist

**Comment by rmillikin** [comment]
I removed this mod in #1512 along with a few other ones.

These seem weird to treat as mods for the above reasons (ambiguity, handling it in 2 places [mods and missed cleavages]) but also because we didn't even check to see if the previous amino acid is a K, to my knowledge...

We could write code for interpreting mass-differences as truncations, unsearched missed cleavages, etc. in an open-mass search. not sure how we should approach it in a notch search, if at all

**Comment by rmillikin** [comment]
we have protease-specific mods now ("AspN Digested", "Trypsin Digested"). "Trypsin Digested" includes GG on K. I think this issue has already been resolved but maybe I'm misinterpreting...
