### ISSUE TITLE
Index-ion searches should have a separate index for each set of digestion parameters

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1108]
We should be generating one index per set of digestion parameters. Right now we're generating one big index for all digestion parameters aggregated together which is probably riddled with errors.

**Comment by rmmiller22** [comment]
@zrolfs edits to non-specific search may have remedied this issue in that now since a search is performed on each file individually and each file is only associated with one protease you only need to generate the index for the protease in the file specific parameters. He essentially eliminated the use of the list of digestion parameters for index based searches

**Comment by zrolfs** [comment]
Fixed in #1434
