### ISSUE TITLE
file type confusion in load

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1142]
Here is output from spritz where we get an unrecognized file type error. I know this happens for other files, where I think that it shouldn't. There should be a way to isolate the final .### and identify it as the file type and ignore all the previous "."s 

SRR1025675_1-trimmedAligned.sortedByCoord.outProcessed.out.fixedQuals.split.snpEffAnnotated.protein.fasta

**Comment by rmillikin** [comment]
This is how Path.GetExtension() works; it isolates the text after the last "." and uses this as the extension. I decided to not use that function because it messed up .xml.gz (it thought the extension was .gz). So what it does now it is assumes that whatever is after the first dot in the filename is the extension. There may be a more complex/robust way of handling that but I think the easy answer is just to remove the dots in the filename except the one before the extension

**Comment by trishorts** [comment]
I'd like to have it handle the more complex scenerio. Anything ending in .gz should be examined again to see which bin it goes to (either raw file or database). That way we can use compressed for everything. This is not urgent, but I would like it to get done. Early job for the next undergrad.

**Comment by rmillikin** [comment]
see #1164
