### ISSUE TITLE
Run failed, Exception: Specified argument was out of the range of valid values. Parameter name: toExclusive

### ISSUE THREAD

**Issue by gvinterhalter** [smith-chem-wisc/MetaMorpheus#1170]
Hello,

I might be doing something wrong, but every time I do a search I get the error in the title and this output:
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2004338/results.txt)

I have to turn of the Quantification. This happens with default settings, where I haven't changed a thing.
Also, after the error I can't "Reset Tasks", so I have to close the software which sucks.

**Comment by rmillikin** [comment]
Sorry to hear about the crash! I can take a guess at the cause but I want to get a little bit more information. I noticed that you're missing MSFileReader, which MetaMorpheus requires in order to read .raw files. Are you searching a .raw or a .mzML spectra file?

The crash does happen in the quantification part. It sounds like either it's an MSFileReader problem or there is something odd with the spectra file, if it's an .mzML.

If you are indeed trying to search a .raw file, please go here: 
https://thermo.flexnetoperations.com/control/thmo/search?query=MSFileReader+3.0+SP2
and download and install MSFileReader.

**Comment by gvinterhalter** [comment]
I indeed use an .mzML which was obtained from .mgf (MSConvert, default options).
I don't have accesses to the link you provided, but I will always only work with .mgf or .mzML.

**Comment by rmillikin** [comment]
Ok, thanks for narrowing it down. I guess the problem must stem from the conversion process. Are you able to share the .mzML or the .mgf file with us? I can try to reproduce this issue.

Please send your file to rmillikin@wisc.edu . I can provide a link to a Box folder if you don't have anywhere to upload the file to.

**Comment by rmillikin** [comment]
Ok, I think I've figured this out. It looks like .mgf only stores MS2 scans with a precursor mass, and no MS1 scans (at least in the file I looked at). MetaMorpheus handles this ok but FlashLFQ (which uses MS1 scans for quantification) crashes. I'll add a requirement for MS1 scans to be present before quantification is run so that this doesn't produce a crash.

**Comment by rmillikin** [comment]
I've fixed FlashLFQ to not crash if there are no MS1 scans found. The fix is applied in #1225 . I'll make a new release soon, likely Monday, with this change.
