### ISSUE TITLE
matched ion 'number and type' in output + 'Matched Ion Intensities' documentation

### ISSUE THREAD

**Issue by ftwkoopmans** [smith-chem-wisc/MetaMorpheus#1233]
I'm composing transition lists directly from MetaMorpheus output with a simple R script. Most information I need is present in .psmtsv already, but I could use some pointers (and possibly extra output columns) with the last few pieces of data.

For each matched ion I need:

1. Fragment number and type (eg; "y7")
2. Fragment intensity
    - #1205 'Matched Ion Intensities' probably contains this data, but I cannot find any documentation on the ordering of these nested arrays (I assume they represent b and y, or y and b, series? But which fragment numbers are these? Maybe you can add a fragment type+number array aligned with the other 'Matched Ion' arrays? )
3. Fragment m/z (theoretical)
4. Fragment Charge

Optionally, I could get 3 and 4 by re-computing with some R package (but getting everything out of the search engine would be ideal).

**Comment by zrolfs** [comment]
1. I think this is a great idea! I'll get on that and make a new column. It'll use the same nested arrays used in #2. I plan to include charge information here as well, so instead of y7, it'll be y7+z.
2. Matched Ion Intensities is a new feature that should achieve what you're interested in. The order of the nested arrays is the same as for the Fragment m/z (theoretical), which is b-y-c-zdot. Adding in #1 will hopefully alleviate the confusion.
3. Fragment m/z (theoretical) is present in "Matched Ion Masses", in the form of masses rather than m/zs. I'll change this to reflect theoretical m/zs, which makes more sense.
4. MetaMorpheus currently only searches for z=1 fragment ions. We're interested in searching for z=2 fragment ions for z=3+ precursors, but we haven't gotten around to it yet.

**Comment by trishorts** [comment]
Zach. will you please edit the related entries in the wiki once your new code is added? https://github.com/smith-chem-wisc/MetaMorpheus/wiki/Glossary-of-Terminology

current headings that need improvement are: 

Matched Ion Counts

Matched Ion Mass Diff (Da) -- The absoulte mass difference between the identified peptide theoretical mass and the mass of the experimental reported as the BestMassInPrecursor.

Matched Ion Mass Diff (Ppm) -- The ppm mass difference between the identified peptide theoretical mass and the mass of the experimental reported as the BestMassInPrecursor.

Matched Ion Masses

**Comment by rmillikin** [comment]
I think we should retool this output to contain maximal information in a machine-parseable format. 

Something like:
[b1;T:193.92827;E:193.92738;I:8198,b2 ... ][y1 ... ]

Describing the ion type/number, theoretical m/z, experimental m/z, and intensity for each ion in a manner that is obvious how they are connected. PPM error can easily be computed, I don't see much need to have that as a column. 

Having separate columns for these fields is difficult to parse, especially when one or more fields is unlabeled.

Thoughts?

**Comment by zrolfs** [comment]
I understand what you mean, but I think it loses human readability when condensed into a single column like that.

I really like the ppm error for fragment mass tolerances, because it lets users quickly see the error associated with the MS2s and get a feel for the quality of the data (ie low res). I'd be more inclined to remove the absolute since it's less informative on data quality.

These columns can be readily parsed by using the index of each position, since all positions are shared between the columns. I agree that a single line would make it easier parse, but I feel that it's difficult to visually understand the information in the column.

**Comment by rmillikin** [comment]
I agree about the human readability. the single column is easier to machine-parse but is quite dense for a human to read. I'm ok with them being separate columns for that sake. I do also think all of the columns should be labeled with b1, b2, etc. for the sake of clarity even though it's redundant.

**Comment by zrolfs** [comment]
Done in #1234

**Comment by zrolfs** [comment]
The new information will be available in 0.0.284.

**Comment by ftwkoopmans** [comment]
Thanks a lot, the new output columns are exactly what I was looking for

**Comment by rmillikin** [comment]
Reopening this issue temporarily. 0.0.284 was supposed to have this info but it is now missing, probably because of a change I made. This will likely be pretty quick to fix and I will make a new version (0.0.285) with this feature.

**Comment by rmillikin** [comment]
this is in 0.0.285 :)
