### ISSUE TITLE
Adding biological replicates to experiment design causes crash

### ISSUE THREAD

**Issue by PeptideWitch** [smith-chem-wisc/MetaMorpheus#1308]
Hi there,

I've been using MM over the weekend and came across this issue when I tried to combine my biological replicates together.

`Run failed, Exception: Array dimensions exceeded supported range.'

Attahced is the result.txt output, and also a screenshot of the setup. 

I've run these raw file sets independently (B1 fractions only, B2 fractions only) using both the modern search and calibrate -> search functions. Both times, I specified the raw files as fractions 1-8, biological rep 1, and they both worked perfectly! It seems that when MM tries to work with them together, it causes some trouble. I've also tried a more sensible experiment (2 conditions, 6 biological reps each, 8 fractions each), and I get the same array dimension error.

[LFQ Flash module is enabled - if that helps]

[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2217676/results.txt)

![replicateerror](https://user-images.githubusercontent.com/33736978/43053207-caed8526-8e6e-11e8-92ff-811fe4f4a5cf.png)

**Comment by rmillikin** [comment]
Thanks for the report! It sounds like you're running out of memory at some point in the analysis (in the specific results.txt you linked, it happens during the FDR analysis stage). That's why when you break up the dataset into pieces, it works. You're only analyzing 16 files though, and 32GB RAM should be plenty to handle that.

We can look into making MetaMorpheus more RAM-efficient. Are you able to share any of this data with us, even just the subset 16 files that cause the crash? That would help us diagnose the problem. You can email me at rmillikin@wisc.edu and I can set up a Box folder, if you're able to share. If not, I can find a large dataset on our end.

**Comment by PeptideWitch** [comment]
Just sent you an email - thanks for looking into this! I'll try a few more things on my end and see if I can get a replicate comparison working.

**Comment by rmillikin** [comment]
I've been in contact with @PeptideWitch and he was able to get this to run by using Classic Search instead of Modern Search. Modern is pretty RAM intensive, and the computer just ran out of RAM. We can look into making Modern less RAM-intensive, but for now, one tip is to split the database into partitions.
