### ISSUE TITLE
Add delta score to psms tsv output

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#135]
stuff I'd like added or changed:

- [x] Add filename to each scan
- [x] Separate protein accession and protein description
- [x] Include sequence without PTMs
- [x] Mark contaminants
- [ ] Add delta score
- [x] Add intensity
- [x] Add retention time
- [x] Include protein location (start residue at least, stop if desired)
- [x] Include units for precursor mass error

**Comment by stefanks** [comment]
Delta score between the current best match and the second best match, right?
Can this second best match be the same peptide but have different modifications? How about the same base sequence, but with modifications that could possibly have only come from a different protein? 
How about the case when the second best match is the same seqeunce but with/without a certain missed cleavage? Say, by adding a K at the C-terminus.
I need more info before adding this.

**Comment by stefanks** [comment]
Zach: I'm interested in what the sequences and the scores are for "runner up" IDs in MetaMorpheus. It would be useful to have another .ptm output file that included, say, the top 10 matches for a given spectra. We would expect to see big score differences between high confidence identifications and the runner up, but could be a way to improve FDR if the score difference is small. I'd also like this for the fusion peptide work, since some psms are assigned correct ids, well others are not, despite being similar MS2 scans.

**Comment by stefanks** [comment]
Shortreed: This is no longer so straight forward. I think second best match could be peptide with mod in another position. That would indicate lack of confidence in localization. A big concern I'm having is that second best match could be a co-isolated peptide. I wonder if we need to allow for this probability. I do not think that second best match can have a different isolation mass (e.g. missed cleavage). But, if you mean that the identified peptide had an allowable mass shift like in gptmd first pass, then I think that would be okay.

**Comment by stefanks** [comment]
Co-isolation is no longer an issue, runner up would not be a co-isolated peptide if narrow precursor tolerance is used.

**Comment by zrolfs** [comment]
I know Lei uses something like this for his XL search. Might be easy to implement using that code.

**Comment by trishorts** [comment]
with co-isolation this loses its relevance.

**Comment by zrolfs** [comment]
No, it doesn't. Coisolation is for PSMs with different precursors. This is regarding what the next highest scoring theoretical is for the same precursor. A small delta score draws attention to homologous database sequences. I high delta score could improve confidence that the assigned sequence is really what it says it is.

**Comment by trishorts** [comment]
True. Yes.

**Comment by trishorts** [comment]
But, you have to be very careful about what you mean by "same precursor" because we have coisolation of peptides whose precursor mass is only a few ppm apart.

**Comment by zrolfs** [comment]
As I understand it, that happens because there were two experimental peaks in the MS1 that were only a few ppm apart? If they're within the allowed, won't the same theoretical be assigned to both?

**Comment by stefanks** [comment]
So if I understand everyone correctly, we could have two columns:

- Delta score to the next best scoring match. This could be the same exact peptide but with a modification on a different amino acid.
- Delta score to the next best scoring match with a different base sequence.

Would those two be interesting/relevant? Any other delta scores that I missed?

**Comment by lonelu** [comment]
Delta score with the first decoy? (Not sure, just add here.)

**Comment by zrolfs** [comment]
Sorry to make more work, but can we also get a delta score with the next best scoring TARGET sequence? The rationale being that similar target sequences have greater difficulty being accurately identified, because they produce similar fragmentation patterns and internal fragments will more easily produce a false-positive identification.

**Comment by stefanks** [comment]
Easiest to implement at the moment is match to next best scoring peptide. It would simply require saving the score of the previous best match in the addorreplace method of PSM. Then it could be output in the tsv file. This is a small job.

The other, more interesting score diffs would require pretty major refactoring, since we're dealing with compactpeptide objects, that have no awareness of target/decoy/base sequence. I may be wrong though.

**Comment by zrolfs** [comment]
No, you're correct. The others would require more work. We could give compact peptide a target/decoy bool object, but I don't really like that.

**Comment by stefanks** [comment]
I don't like that either.

A solution could be saving all matching peptides with a score above cutoff in the PSM, but I'm not sure how that would affect memory consumption.

**Comment by zrolfs** [comment]
It also wouldn't work if there wasn't another compact peptide scoring above the cutoff. This would throw off the delta score for PSMs with lower scores.

**Comment by zrolfs** [comment]
We could search targets and decoys separately?

**Comment by stefanks** [comment]
I was thinking these could be marked with delta score infinity

**Comment by stefanks** [comment]
T/d separately: interesting idea

**Comment by zrolfs** [comment]
In my mind, here are benefits to these scores (First score is always highest scoring ID, so there would only be two of the four for each PSM):
T-T (HighestScoringTarget - SecondHighestScoringTarget): Used to find a false-positive rate, where a high delta score provides more confidence that the correct ID was made.
T-D (HighestScoringTarget - HighestScoringDecoy): Used to assess probability of randomly low T-T.
D-T (HighestScoringDecoy - HighestScoringTarget): Used to find a false-negative rate, where a low delta score suggests that the scan was perhaps the target sequence (Caution, can't be used at low (<10) scores).
D-D (HighestScoringDecoy-SecondHighestScoringDecoy): Used to assess probability of randomly low D-T.

**Comment by rmillikin** [comment]
this is done thanks to Zach
