### ISSUE TITLE
Crash in non-specific search

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1371]
Katie reported this crash. It occurs in v288 and v287. Unsure about previous versions.

[SearchTaskconfig.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/2315050/SearchTaskconfig.zip)
[results.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/2315060/results.zip)

Data files are on bison; ask me for the folder

**Comment by zrolfs** [comment]
This is looking like an mzlib issue. The key is present in the dictionary, but the program isn't calling them as equal (same values, but not the same object). I presume that the Equals() override was deleted, but I can't tell from the history because the old CompactPeptideWithModifiedMass is no longer present in mzlib.
