### ISSUE TITLE
Delta score and ambiquity

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1402]
delta score = 0 for ambiguous peptides (not using third best peptide).

**Comment by zrolfs** [comment]
Are you sure? That shouldn't be possible. The second best scoring peptide is required to not have the same score as the highest scoring peptide.

`        public void AddOrReplace(PeptideWithSetModifications pwsm, double newScore, int notch, bool reportAllAmbiguity, List<MatchedFragmentIon> matchedFragmentIons)
        {
            if (newScore - Score > ToleranceForScoreDifferentiation) //if new score beat the old score, overwrite it
            {
                _bestMatchingPeptideWithetMods.Clear();
                _bestMatchingPeptideWithetMods.Add((notch, pwsm));

                if (Score - RunnerUpScore > ToleranceForScoreDifferentiation)
                {
                    RunnerUpScore = Score;
                }

                Score = newScore;

                PeptidesToMatchingFragments.Clear();
                PeptidesToMatchingFragments.Add(pwsm, matchedFragmentIons);
            }
            else if (newScore - Score > -ToleranceForScoreDifferentiation && reportAllAmbiguity) //else if the same score and ambiguity is allowed
            {
                _bestMatchingPeptideWithetMods.Add((notch, pwsm));

                if (!PeptidesToMatchingFragments.ContainsKey(pwsm))
                {
                    PeptidesToMatchingFragments.Add(pwsm, matchedFragmentIons);
                }
                else
                {
                    //TODO: Do we need to do anything????????????????? if the thing is already there?
                    throw new MetaMorpheusException("Cannot add duplicate peptides to the same PSM!");
                }
            }
            else if (Score - RunnerUpScore > ToleranceForScoreDifferentiation)
            {
                RunnerUpScore = newScore;
            }
        }`

**Comment by zrolfs** [comment]
Perhaps I'm confused; do you mean that ambiguous peptides currently have delta scores of zero, or that they should have delta scores of zero but currently do not?
The argument against having a delta score of zero for ambiguity is that the user can already see the other possible ambiguous matches. Additionally, PTMs that are unlocalized get delta scores of zero.

**Comment by trishorts** [comment]
I think PTM localization is a different issue than ambiguous base sequences. Ambiguous base sequences could (probably) come from different proteins wherease the ptm thing is simply that we dont have fragmentation evidince. one can be used in parsimony and quantification and one (the sequence ambiguous assignment) cannot.

**Comment by zrolfs** [comment]
I think I understand. In my mind, ambiguity means that there isn't a best peptide, but there's a best group of peptides. So in that case, the delta score is currently the score between the highest and second highest scoring peptide groups. 
I'm not a huge fan of removing additional information (the score difference is between peptide groups), when the ambiguity information (delta score = 0) is already known (because there are multiple full sequences). The user can always override the delta score for ambiguous peptides, but they can't go back and find the delta score between peptide groups.

That being said, I don't have any investment in delta scores. If making this change helps us with something, then we should do it.
