### ISSUE TITLE
Put spectrum loading in background for annotation metadraw

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1456]
spectra in raw files can be addressed individually, so maybe we don't even have to load the whole thing for the viewer to work. just load the active spectrum.

Also, we could background the loading and let folks get started on what is loaded. 

The waiting is the hardest part. 

Maybe update the loading bar with a %completion based on spectrum number?

Probably should only load spectra with some sort of identification and not load all the spectra

**Comment by rmillikin** [comment]
we don't have dynamic scan loading for mzML so that would only be possible for .raw files (which would be nice)

% loading - needs to be an mzLib change. The mzLib file loading doesn't report any progress.

At one point we did allow plotting of scans even without a PSM (you could view the unannotated spectrum). Might be kind of nice to retain this feature

**Comment by rmillikin** [comment]
this was fixed at some point but i forget the PR number
