### ISSUE TITLE
Questions on parameters

### ISSUE THREAD

**Issue by vokelvin** [smith-chem-wisc/MetaMorpheus#1496]
Hi rmillikin,

I am currently trying to run a crosslinking search on a raw file. My inexperience with MetaMorpheus limits me. I am wondering what these parameters mean and what would be reasonable numbers for each: 

- peak trimming
- max threads
- max modification isoforms
- top N peptides per precursor
- deconvolute precursors
- number of database partitions

When I ran the set of test files, everything went fine. But I can't seem to get calibration on my database to function properly. I'm wondering if this is caused by settings. Should default parameters be working? 

Thank you, 
Undergraduate

**Comment by zrolfs** [comment]
Hi vokelvin!

**peak trimming**: In this step, we are removing low intensity peaks from the MS1 and MS2 spectra (if specified). This prevents noise from incorrectly assigned as a peak. We keep the top N most intense peaks, and require a minimum ratio of the peak intensity to the highest peak in the spectrum.
**max threads**: This is the number of threads that your CPU can use to run MetaMorpheus. The more threads, the faster the search will go. The default number is the the maximum number of threads your CPU has (minus one, so your computer won't freeze on you).
**max modification isoforms** This is the maximum number of peptidoforms that can be generated from a single peptide. If you have lots of possible modifications on a peptide, the combinations of all different modifications can cause a massive number of uniquely modified sequences. This parameter caps the combinatorics to prevent it from straining your computer.
**top N peptides per precursor** I don't see this parameter, sorry! @rmillikin 
**deconvolute precursors** This allows MetaMorpheus to deconvolute your data. The instrument used to acquire data often does a poor deconvolution compared to MetaMorpheus. Additionally, this parameter allows MetaMorpheus to identify coisolated peptides (multiple peptides from a single MS/MS).
**number of database partitions** This is useful for Modern, Semi, and Nonspecific search modes (indexed search modes). If you are doing a search and run out of RAM, you can increase the number of database partitions to decrease the amount of active memory. This does not change the outcome of the results.

**Comment by zrolfs** [comment]
Additional information regarding parameters can be found in our wiki:
https://github.com/smith-chem-wisc/MetaMorpheus/wiki/New-Search-Task:-File-Loading-Parameters

**Comment by trishorts** [comment]
Can we get this added to the wiki?

**Comment by zrolfs** [comment]
I believe it's in the wiki.

**Comment by rmillikin** [comment]
I'll just add something about the top N peptides per precursor here. The crosslink search works by:
1. Doing a completely open-mass search for all peptides in all spectra (ignoring experimental precursor mass)
2. All peptide options that meet the fragment score cutoff are paired together and their masses are summed (plus crosslinker mass) to see if they make the precursor mass
3. The total XL score is the score of the two summed peptide scores

the top N reduces the number of peptides allowed in step 1 to the top N scoring peptides (default is top 300). 

example: 
The crosslinker mass is 100 Da. 
Peptide A has a mass of 1100 Da and a score of 11. 
Peptide B has a mass of 900 Da and a score of 9. 
Peptide C has a mass of 800 Da and a score of 10. 

Peptides A, B, and C meet the score cutoff for an MS2 scan with a precursor mass of 2100 Da. 
A+B+crosslinker: 2100 Da
A+C+crosslinker: 2000 Da
B+C+crosslinker: 1800 Da

Only A+B+crosslinker matches the precursor mass (2100 Da), so that's chosen as the hit even though A+C has a higher fragment score. Peptide C may be a separate, coisolated peptide that's not crosslinked to anything, or a false-positive, etc.

This would be an example of "top 3" peptides per precursor.

**Comment by vokelvin** [comment]
Hi zrolfs, 

The error messages are as follows:

"Could not find enough PSMs to calibrate with; opening up tolerances to 20 ppm precursor and 50 ppm product
Could not find enough PSMs to calibrate with; opening up tolerances to 30 ppm precursor and 100 ppm product
Could not find enough PSMs to calibrate with; opening up tolerances to 40 ppm precursor and 150 ppm product
Calibration failure! Could not find enough high-quality PSMs. Required 20, saw 0
Calibration failure! Could not find enough MS1 datapoints. Required 50, saw 0
Calibration failure! Could not find enough MS2 datapoints. Required 100, saw 0"

This is confusing to me because I was told that the particular files I am using generate good data. The crosslink search of my raw file works, but calibration does not. Is there something I'm missing, or another factor I didn't consider? If most of my peptides are X linked, then what can I do about that?

**Comment by rmillikin** [comment]
that's kind of odd - do you have any uncrosslinked peptides in your sample at all? Or are they all crosslinked?

Calibration doesn't search for crosslinked peptides currently, it can only find single peptides. If your sample is entirely composed of XL peptides then you can't calibrate, unfortunately. the XL search will still work, though

**Comment by vokelvin** [comment]
Sorry for the late reply! The issue has been fixed. It was an error on our part; I was given the wrong DB for the raw file I was using. Calibration now works, along with XL search. Thank you for the help.

**Comment by rmillikin** [comment]
lol! that must have been frustrating. glad it worked out. feel free to ask for more support.
