### ISSUE TITLE
MetaDraw: load a complete set of files

### ISSUE THREAD

**Issue by JesseIL** [smith-chem-wisc/MetaMorpheus#1527]
Hello,
MetDraw is great but in typical experiments we include many raw files and thus to view annotated MS2 spectra of peptides from a protein of interest requires loading files one by one. This is impractical and is one of the reasons why we have not started using MM as our main software. 
Is it possible to have MD upload several files and summarize the IDs from all files in one table?
Thanks,

Yishai

**Comment by rmillikin** [comment]
Hi Yishai,

This is certainly possible. We have several MetaDraw updates planned and we can add this to the list. The main reason you can only currently load one file is RAM usage.

**Comment by lonelu** [comment]
One way to avoid heavy RAM is to load scans that are identified. Filter by scan number.

**Comment by rmillikin** [comment]
I've made a PR for dynamic .mzML and .mgf connections so that we can load single scans out of a spectra file, which would enable us to "load" as many files as we want. we'd just load the scan from the file being requested for the current annotation. we already have dynamic connection for thermo .raw. https://github.com/smith-chem-wisc/mzLib/pull/501

**Comment by rmillikin** [comment]
This was implemented in #1926 and is part of releases 0.0.309 and later
