### ISSUE TITLE
The spectrum ids in the mzIdentML file are not correct Thermo ids

### ISSUE THREAD

**Issue by yishai99** [smith-chem-wisc/MetaMorpheus#1654]
Hi,
I was trying to build a library in Skyline and received an error. Their support people say that the spectrum ids in the mzIdentML file are not correct Thermo ids: "scan=1234". 
It is listed under issue ID 648 on Skyline support page.
Can you check this? Are you able to create a spectrum library from results from MetaMorpheus?
Thanks,

Yishai

**Comment by trishorts** [comment]
thanks for creating this issue. I hope that we can look at it today. Here is a link to skyline issue https://skyline.ms/issues/home/issues/details.view?issueId=648

**Comment by rmillikin** [comment]
Ok, I think I understand the problem. The Thermo scan IDs in the mzID file are not formatted properly, I guess.
Instead of: "scan=1234"
We should use: "controllerType=1 controllerNumber=0 scan=1234"

This scan ID is correct in our written mzML files but not our mzID files, apparently. I'll test to see if I can fix this and get back to you, hopefully today.

**Comment by rmillikin** [comment]
I got Skyline to read our mzID with the following steps:
1. Change .mzID to .mzid
2. Find+Replace:
Find: spectrumID="scan=
Replace with: spectrumID="controllerType=0 controllerNumber=1 scan=
3. Put the .mzML file into the same directory as the .mzID file

I'll see about correcting our scan headers so you don't have to do step 2.

**Comment by rmillikin** [comment]
Thanks for your patience. I've fixed this in #1685 and it will be in the next release
