### ISSUE TITLE
Possible problems for MS2 scan deconvolution

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1672]
1. GetNeutralExperimentalFragments() use charge state from minZ = 1 to maxZ = 10. 
Some other software only use charge state from minZ = 1 to maxZ to 'precursor charge'.

2. We default trim MS2 scan with: top 200 intensity 0.01.
Deconvolution is performed after trimming the scan. It is possible that isotope peaks are filtered and the deconvolution is wrong. How often does this happen is unknown.

**Comment by lonelu** [comment]
Rob's comment from slack:
it definitely happens. if there's a peak that can't be deconvoluted (meaning there are no isotope peaks) it's assumed to be a charge 1 peak (unless you're doing top-down, in which case the peak is removed from the spectrum). we could try doing deconvolution before peak filtering, but it would require some code restructuring and it would probably make searches take longer

also the ppm tolerance for MS2 deconvolution is 4ppm right now and I don't think there's a way to change it
so it's very conservative for what MM calls a higher-charge fragment

**Comment by rmillikin** [comment]
`z=1 to z=10` is used instead of `z=1 to z=precursor` because of co-isolation. just because a particular precursor has z=2 doesn't mean that there's nothing else in the scan higher than z=2. I know that's kind of nitpicky, but it results in false-positives. Instead, we have a rule that a theoretical ion can't be matched if the experimental fragment has a higher charge than the precursor ion (see line 124 in MetaMorpheusEngine.cs). in other words, the MS2 deconvolution is not precursor-charge dependent, but ion matching is.

**Comment by rmillikin** [comment]
Anyway, as far as deconvolution mass tolerances and peak filtering go, it's data-dependent. the calibration task suggests PPM search tolerances now. we could suggest keeping top N peaks for a particular file, or suggest MS1/MS2 deconvolution PPM tolerances via the calibration task.
