### ISSUE TITLE
MS File Reader 3.0 SP3

### ISSUE THREAD

**Issue by DanItzhak** [smith-chem-wisc/MetaMorpheus#1682]
MetaMorpheus 0.0.301 running with MS File Reader 3.0 SP3

Run failed, Exception: Could not load file or assembly 'ManagedThermoHelperLayer.dll' or one of its dependencies. The specified module could not be found.

I checked that ManagedThermoHelperLayer.dll is in the program folder of MetaMorpheus

Could it be that MS File Reader 3.0 SP3 is not supported? This is the only version available from Thermo.

**Comment by DanItzhak** [comment]
Also tried with MS File Reader 3.1 SP2, also failed.

"Warning! Thermo MSFileReader is not version 3.0 SP2; a crash may result from searching this .raw file"

**Comment by trishorts** [comment]
Sorry that your having problems. I would think that sp3 would be fine but since you also have sp2, i guess that's not the culprit,  Couple things You could check to see if you have the latest Microsoft C++ Redistributable. Also, the crash should have created a Results.txt file that will have some information that maybe useful in diagnosing the problem. Would you check on the existance of that file and post its contents here? Last, did you try running the vignette? Was that successful?

**Comment by DanItzhak** [comment]
Thanks for getting back so quickly. 

C++ Redistributable was not up to date, and this appears to have solved the issue! 

Here is the results file for reference in any case. 
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3317332/results.txt)

Thanks again

**Comment by trishorts** [comment]
I'm delighted that worked. Thanks also for sending the file. Please don't hesitate to reach out with any questions you have.
