### ISSUE TITLE
Modification name in mzID file

### ISSUE THREAD

**Issue by wenbostar** [smith-chem-wisc/MetaMorpheus#1684]
In the output mzID file of MetaMorpheus, the names of some modifications are "unknown modification". But as shown below, they are present in UNIMOD so there should have names defined in UNIMOD for these modifications.

```
    <Peptide id="P_8928">
      <PeptideSequence>TVLLPNHAGCAGFANEDR</PeptideSequence>
      <Modification location="10" residues="C" monoisotopicMassDelta="57.021463721">
        <cvParam name="Carbamidomethyl on C" cvRef="PSI-MS" accession="UNIMOD:4" />
      </Modification>
    </Peptide>
    <Peptide id="P_8929">
      <PeptideSequence>INELEIWYDEMSLEDLSDQSISRDFPPK</PeptideSequence>
      <Modification location="11" residues="M" monoisotopicMassDelta="15.99491462">
        <cvParam name="Oxidation on M" cvRef="PSI-MS" accession="UNIMOD:35" />
      </Modification>
    </Peptide>
    <Peptide id="P_8930">
      <PeptideSequence>NYSENTDKDLSR</PeptideSequence>
    </Peptide>
    <Peptide id="P_8931">
      <PeptideSequence>NTPSMQALGESPESSSSELLNLGEGLGLDSNR</PeptideSequence>
    </Peptide>
    <Peptide id="P_8932">
      <PeptideSequence>KASNGNARPETVTNDDEEALDEETK</PeptideSequence>
      <Modification location="4" residues="N" monoisotopicMassDelta="0.984015583">
        <cvParam name="unknown modification" value="Deamidation on N" cvRef="UNIMOD" accession="MS:1001460" />
      </Modification>
      <Modification location="8" residues="R" monoisotopicMassDelta="0.984015583">
        <cvParam name="unknown modification" value="Citrullination on R" cvRef="UNIMOD" accession="MS:1001460" />
      </Modification>
```

**Comment by rmillikin** [comment]
Thanks - I'll look into this, probably tomorrow. I'm not sure the cvPram `name` is correct for the other mods either. I don't think I need your data to look into this, but I'll let you know if I do.

**Comment by rmillikin** [comment]
I see what the issue is. We have our own list of PTMs with names, masses, chemical formulas, etc. that we have manually annotated, and those are used by default by MetaMorpheus (in G-PTM-D, etc). We are able to manually annotate the equivalent Unimod ID but we have only done so for Oxidation of M, Carbamidomethylation of C, and Carbamidomethylation of U. We can go through all of our mods and find the equivalent Unimod ID and then annotate them in our PTM list. This is fairly labor intensive but I'll look into finding some resources to make this happen. 

If you need Unimod IDs for all your annotated modifications now, you can perform G-PTM-D and searches with mods from the `Unimod` mod category instead of `Common Biological`, etc. All of these Unimod modifications come directly from our downloaded list of mods from Unimod, all annotated with their Unimod IDs. Their list of mods is quite long so it can be inconvenient to find the particular modifications you want in their giant list. But the search function should help a bit.

**Comment by wenbostar** [comment]
Thanks. 
For the specific case as shown below, The UNIMOD ID for the modification is clear and present there, but why is the name still "unknown modification"?
```html
<Peptide id="P_8932">
      <PeptideSequence>KASNGNARPETVTNDDEEALDEETK</PeptideSequence>
      <Modification location="4" residues="N" monoisotopicMassDelta="0.984015583">
        <cvParam name="unknown modification" value="Deamidation on N" cvRef="UNIMOD" accession="MS:1001460" />
      </Modification>
      <Modification location="8" residues="R" monoisotopicMassDelta="0.984015583">
        <cvParam name="unknown modification" value="Citrullination on R" cvRef="UNIMOD" accession="MS:1001460" />
      </Modification>
```

**Comment by rmillikin** [comment]
I'll take the first mod as an example. 

`Deamidation on N` is the name we've given to a modification - that's a modification that our lab has annotated in MetaMorpheus's text files. It's not a Unimod modification, it's a separate entity. There is [an equivalent Unimod modification](http://www.unimod.org/modifications_view.php?editid1=7) called `Deamidation` with an accession of 7, but MetaMorpheus doesn't know that the two modifications are equivalent. 

So when you do a search with MetaMorpheus and find this `Deamidation on N` mod, MetaMorpheus calls the Unimod name `unknown modification` because it doesn't know the name of the Unimod equivalent until we annotate it in MetaMorpheus's text files.

**Comment by rmillikin** [comment]
I added a lot of Unimod accessions to our mods in #1687 . Some are missing, but this should cover the vast majority of cases.

**Comment by wenbostar** [comment]
I see. Thank you very much.

**Comment by rmillikin** [comment]
This change is in 0.0.302 (i.e., a lot of MetaMorpheus's mods have their UniMod equivalent annotated and present in the mzIdentML). Please reopen this issue or create a new one if you encounter similar issues or you have a suggestion for an annotation.
