### ISSUE TITLE
Superfluous .toml stuff (maybe?) or at least confusing

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#1709]
![image](https://user-images.githubusercontent.com/16841846/62729289-46ea8480-b9e3-11e9-9054-3457d58364f1.png)

**Comment by rmillikin** [comment]
this might be semi- and non-specific cleavage related? like if you do semi-specific lysC those two values will be different I think. @zrolfs ?

**Comment by zrolfs** [comment]
Yes, Rob is correct. The Protease is what is being used for the digestion. The SpecificProtease is used for specificity-based FDR stratification. I explained that to @trishorts earlier today, so perhaps this issue is more about confusion with the name? We could rename it something obnoxious like "SpecificProteaseThatWasAppliedToTheSampleButNotTheInSilicoDigestionButIsUsedForSemiAndNonSpecificSearchFdrCalculations", if that would make @trishorts happier.

**Comment by zrolfs** [comment]
We could also maybe set it the default to null, and then the toml won't write it. Not sure if that will create a crash.
