### ISSUE TITLE
Crash during output when analyzing data with Spritz database

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1731]
A PSM file was written, but not sure it made it all the way through.
Database: \\bison\share\Users\Zach\NOD_Spritz\combined.spritz.snpeff.protein.withmods.xml.gz
Results.txt: [results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3602331/results.txt)

**Comment by trishorts** [comment]
was this a search with several raw files? do you know which file produced the crash

**Comment by zrolfs** [comment]
It was with 12 raw files. Not sure which one is responsible. I've put the files on bison in the same folder as the database.

**Comment by acesnik** [comment]
It died when writing a sequence variant string... @rmmiller22, any thoughts?

**Comment by rmmiller22** [comment]
Although I cannot be 100% confident. I encountered the same crash message and have since made edits in mzLib that remedy this bug. It is not in the release version. Additionally there are more adjustments to mzLib variant code that have not yet been merged to MetaMorpheus's master branch. I will be making a pull request shortly once I have ran more raw files through to try and more thoroughly test the code for robustness.

**Comment by rmmiller22** [comment]
Variant identification and representation fixes (#511) -- this PR is most likely what in mzLib will fix the bug in MM
The following were additional mzLib PR that handle bugs from the variant specific PWSM methods:
stop gain bug fix (#513)
Fix Variant Psm Crash (#516)
and nterminal protease bug fix (#517)- not yet merged

**Comment by rmillikin** [comment]
has this crash been fixed?

**Comment by zrolfs** [comment]
I'll test.

**Comment by zrolfs** [comment]
No crash in 0.0.303
