### ISSUE TITLE
multiple crosslinking sites

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1737]
Hi Guys,

Is it possible to configure a novel crosslinker to act on multiple sites?

Cheers,
David,

**Comment by lonelu** [comment]
yes, this is one feature people like. Open MetaMorpheus -> Data -> Create New Crosslinker;
If one side of the crosslinker reacts with two or more site such as Lysine or Arg, just input 'KR' in Crosslinker Amino Acids. If the other side of the crosslinker reacts with the same sites, input the same string. Otherwise if different, such as Asp or Glu, just input 'DE'.

**Comment by Dmorgen** [comment]
Thanks!
