### ISSUE TITLE
EngineLayer/GlobalVariables.cs writes into codebase, not allowed in Singularity or HPC 

### ISSUE THREAD

**Issue by jj-umn** [smith-chem-wisc/MetaMorpheus#1818]
Files: CustomAminoAcids/CustomAminoAcids.txt and settings.toml are written into the code base when MetaMorpheus is first run.   

This is an issue when running MetaMorpheus in a Singularity container.   The codebase is in a read only file system for security reasons.  

This could also be an issue for an a HPC system in which multiple jobs could be run concurrently if  the jobs need to alter those files.   

Could there be command line option for a user DataDir that could override or modify defaults rather than writing back into the codebase?

**Comment by trishorts** [comment]
we'll look into it jj

**Comment by rmillikin** [comment]
We could very easily add a command-line option to change the data directory - this seems like the simplest path forward

**Comment by rmillikin** [comment]
I've got this resolved in #1835 but needs testing + unit tests

**Comment by rsdmse** [comment]
While our Docker container works fine on a personal laptop, we're experiencing probably the same issue with the converted Singularity container on a cluster. Here's the complete output:
```
Welcome to MetaMorpheus
Unhandled exception. System.TypeInitializationException: The type initializer for 'EngineLayer.GlobalVariables' threw an exception.
 ---> System.IO.IOException: Read-only file system
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at EngineLayer.GlobalVariables.WriteAminoAcidsFile()
   at EngineLayer.GlobalVariables.RefreshAminoAcidDictionary()
   at EngineLayer.GlobalVariables..cctor()
   --- End of inner exception stack trace ---
   at MetaMorpheusCommandLine.Program.Run(CommandLineSettings settings)
   at MetaMorpheusCommandLine.Program.<>c__DisplayClass3_0.<Main>b__1(CommandLineSettings options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at MetaMorpheusCommandLine.Program.Main(String[] args)
CMD: line 2: 59159 Aborted 
```

**Comment by rsdmse** [comment]
Our user replied that the dev container (converted into Singularity) mentioned in #1835 is working on our cluster. Thanks again for all your help!

**Comment by rmillikin** [comment]
Great to hear! I'll make a new release soon (probably within a week or two). 

For those following this issue:
You can pull the current smithchemwisc/metamorpheus:dev tag from DockerHub which includes this change. the dev tag is a Docker image containing a build of the current master branch.

something like this (assuming you're using Singularity to pull from DockerHub):
![95635857-37395680-0a53-11eb-924b-5cab0c4de230](https://user-images.githubusercontent.com/24705713/96000746-dae08900-0dfc-11eb-9845-55e0a6c637d4.png)

I'll close this issue because it seems to be resolved at this point.
