### ISSUE TITLE
Move "Minimum Allowed Score" to "Output Options"

### ISSUE THREAD

**Issue by azelter** [smith-chem-wisc/MetaMorpheus#1862]
I am running a calibrate->G-PTM-D->search pipeline using more or less default settings in MetaMorpheus.
The search task has output options which allow filtering results to a given FDR. I did not enable filtering.
![output-options](https://user-images.githubusercontent.com/37884518/77481561-21c74c80-6de1-11ea-9304-946394699d7f.png)
I thus expected to see both low and high scoring PSMs in the data output, however when I look at the q value range in results from the G-PTM-D step I see a range form q=0 to q~=0.02 and almost no decoys (invisible on this axis scale which was appropriate for target PSMs). 
![target-decoy-versus-q-all-GPTMD-candidates](https://user-images.githubusercontent.com/37884518/77481611-41f70b80-6de1-11ea-8983-611a41ad1a6a.png)
When I look at the same plot for the post G-PTM-D search task I see a range form q=0 to q~=0.01 and also almost no decoys. 
![target-decoy-versus-q-all-postGPTMDsearch-PSMs](https://user-images.githubusercontent.com/37884518/77481641-53401800-6de1-11ea-8aaf-788c28e3c5ac.png)
It therefore looks to me that the results are being filtered. Is this the case? Is there a way to turn this off? I am looking for PSMs to specific scans that give high quality results in some other search engines. Seeing how these spectra were scored in MetaMorpheus will help me troubleshoot how they are being handled in your software. From the output files I have many spectra seem to be absent. The ones assigned to PSMs seem to all be relatively high confidence assignments.
Thanks!
Alex

**Comment by zrolfs** [comment]
Hi Alex! 
I suspect this is happening because of a the parameter "Minimum Score Allowed" which can be found under Advanced Settings -> Search Parameters -> Scoring Options. It would probably make more sense to include this parameter in "Output Options". Can you please let me know what the lowest scoring PSM is in your output file? If it's ~5, it's likely because of this parameter.

![image](https://user-images.githubusercontent.com/16883585/77482735-a53e6900-6df4-11ea-9e05-5c9dd8725663.png)

**Comment by azelter** [comment]
Thanks for the fast response!
In my 3 task pipeline [1)calibrate; 2)G-PTM-D; 3)search] the task 2 GPTMD_Candidates.psmtsv "Score" column had values from 5.004 to 39.46 and "q" column had values from 0 to 0.020425. The task 3 AllPSMs.psmtsv "Score" column had values from 5.006 to 39.46 and "q" column has values from 0 to 0.012019.
I did not touch the scoring option you mentioned. Thus it looks like you figured out the problem.

I changed the minimum score setting to 1 in both G-PTM-D and the search tasks. This is the smallest number I was allowed. I re-ran the analysis in version 0.0305. The task 2 GPTMD_Candidates.psmtsv "Score" column now has values from 1.001 to 39.46 and "q" column has values from 0 to 0.336302. The task 3 AllPSMs.psmtsv "Score" column now has values from 1.001 to 39.46 and "q" column has values from 0 to 0.183423. 

The missing scans are now present and with low q values as expected so I think your solution solved this problem. For general information I'd love to know if setting minimum score setting to 1 removes all filtering or is there still some filtering going on? If so, is it possible to return all PSMs regardless of score?

Thanks alot for your help!
Cheers,
Alex

**Comment by zrolfs** [comment]
Hi Alex! Glad it worked for you! As you mentioned, the minimum score allowed is 1, which translates to requiring at least one peak matched between the theoretical and observed spectra. If a minimum score of zero was allowed, a random peptide sequence could be assigned to the psm with a score of zero, provided it had a similar precursor mass. This would be the equivalent of assigning an identification from the intact peptide mass. So, in answer to your question, there is still _some_ filtering happening. 

In our experience, any psm that has fewer than 5 peaks matching (and thus a score less than 5) is not a confident identification. Even if it falls within the 1% FDR (q<0.01), it's only appears confident because it's being "buffered" by many high confident identifications with higher scores. For example, if you look at psms with scores of 4, they are likely half targets and half decoys, which implies all of those targets are false-positive identifications.

**Comment by zrolfs** [comment]
As a last note, MetaMorpheus allows for the identification of multiple peptides from a single MS2 because of coisolation (where one peptide was isolated for fragmentation, but multiple peptides were within the isolation window of the MS). There is deconvolution filtering that happens to determine if peptides were coisolated, but these parameters are complex and not available to the user.

**Comment by rmillikin** [comment]
done in #1946
