### ISSUE TITLE
Run failed, Exception: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by bhampton-som** [smith-chem-wisc/MetaMorpheus#1864]
Hello,

MM v0.0.305 (and previous version) crashes at the beginning of the quantification step with this error: Run failed, Exception: Index was outside the bounds of the array.

The reason may be that the raw files were acquired using a 3 segments.  The first and last segments of the run were collected in negative ion mode using the LIT as the detector.  The central main segment is the gradient elution of the peptides collected in positive ion mode using the OT.  I have since changed this so that the detector is the OT for the full 3-segment run and MM doesn't crash.  

These raw files do not cause MQ to crash.  I can provide a raw file upon request if this is something you desire.

Thanks,
Brian

**Comment by rmillikin** [comment]
Thanks for the crash report - can you send a raw file to rmillikin at wisc dot edu?

BTW, are you able to perform a search by disabling quantification? Or does the search fail also?

**Comment by rmillikin** [comment]
I've tested this data and in the intervening time between when this issue was opened and now the crash seems to have been fixed, though I don't know what change specifically fixed it. 

The file in question has ITMS negative mode MS1 for the first segment of the data, FTMS (orbitrap) positive mode MS1 for the majority of the data, and then back to ITMS negative mode. My guess is that negative mode somehow caused a crash but again this seems to have been fixed. 

I also tested a file from http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD004198 as a negative mode test and that also seems to run fine. I'm going to close this for now but feel free to reopen if this is not fixed.
