### ISSUE TITLE
MetaMorpheus 0.0.305 crashes when selecting global settings

### ISSUE THREAD

**Issue by bhampton-som** [smith-chem-wisc/MetaMorpheus#1872]
MetaMorpheus crashes when choosing Settings>Close MetaMorpheus and open global settings file.   I only tried this to see if the option for formatting TSV files for excel was active or inactive.

My system is an HPZ600 Win 10 Pro, dual hex core, 24Gb RAM

**Comment by rmillikin** [comment]
Thanks - are you an admin on that machine? And if you go to `Data -> Open folder with mods/data files`, do you also get a crash?

**Comment by bhampton-som** [comment]
I can open this folder without MM crashing.

Brian

**Comment by rmillikin** [comment]
Ok. Interesting. For the time being, if you want to check on the global settings, they live in that directory - it's the "settings.toml" file. You can just open it in Notepad++ or similar and edit or check on the Excel compatibility. I will try to reproduce this crash and get it fixed.

**Comment by rmillikin** [comment]
Ok I believe I've figured this one out, it's relatively straightforward. MetaMorpheus is trying to open the .toml file and then close the program (i.e., close MetaMorpheus). However Windows doesn't have a program to open the .toml with, so it does nothing instead of prompting you for a program to open the .toml with. So the end effect is MM just closes and nothing happens. 

The quick fix is to associate .toml with a text editing program (i.e., Notepad). Of course most users will not have a program associated with .toml typically, so this is not a super user-friendly fix.

I will fix the code to have .toml open with Notepad by default; this will be in the next release.

**Comment by bhampton-som** [comment]
Great!  Thanks for your help.

Cheers,
Brian
________________________________

**Comment by rmillikin** [comment]
fixed in #1912
