### ISSUE TITLE
Memory usage in G-PTM-D

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#1881]
I'm analyzing ~100 fractions and running out of memory in G-PTM-D. Any suggestions?

![image](https://user-images.githubusercontent.com/16342951/79051148-2cad1a00-7bf4-11ea-9c03-eb743cc3459d.png)

**Comment by zrolfs** [comment]
Yikes. I'm wondering if it has to do with the number of PSMs being saved? The PeptideWithSetModifications objects are kind of cumbersome. @lonelu has been running into RAM issue with crosslinking as well.
If this is the case, one possible solution might be to increase the minimum allowed score. Maybe 8? Not using MetaMorpheus deconvolution would help as well.

You could also do serial GPTMD?

None of these options are very attractive...
Do you know where in the run it's maxing out? I can't tell from the screenshot.

**Comment by acesnik** [comment]
Thanks for all the recommendations, Zach! I might try serial GPTMD next with 1/4 of the experiment each time...

I was running fxns 13-89, and it maxed out at fxn 65.

**Comment by zrolfs** [comment]
To clarify, did it max out during the search or during a post-search task?

**Comment by acesnik** [comment]
It was doing the Classic Search when I canceled the run.

**Comment by MiguelCos** [comment]
Hello, I just came along to support this thread with my experience.

I was testing 24 fractions with G-PTM-D after calibration. The program was 'performing FDR calculations' at the G-PTM-D task when it took all the RAM from our server for itself (>55 GB). The CPU usage was very low at that point. I needed to cancel the run because it was making it impossible for other users to use our server. 

I would try your suggestions later. I was wondering if there are any options to limit the core usage of the computer while running MetaMorpheus.

Best,
Miguel

**Comment by acesnik** [comment]
Increasing the Minimum Score Allowed to 6 or even 7 or 8 should help if you're running into RAM issues. This is under Search Parameters. Most PSMs that pass 1% FDR are well above these scores.

![image](https://user-images.githubusercontent.com/16342951/92504279-0fdb3980-f1c8-11ea-8deb-b0f1dc3d26e6.png)

**Comment by acesnik** [comment]
The option to limit the number of cores for the run is called Max Threads:
![image](https://user-images.githubusercontent.com/16342951/92504833-cc34ff80-f1c8-11ea-9ae7-23df067ea1c0.png)

Hope that helps! -AC
