### ISSUE TITLE
Create a Dark Mode

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1902]
My eyes are burning. Can we make MetaMorpheus black, but have the option to go back?

**Comment by trishorts** [comment]
are there xaml pallettes that can generally apply itself to a whole gui that would make that simple?

**Comment by rmillikin** [comment]
i believe so - I know we can set styles on a page-wide basis. I assume we could do the same for app-wide.

**Comment by rmillikin** [comment]
you can check out some app-wide colors and page-wide styling that is here:
https://github.com/smith-chem-wisc/MetaMorpheus/pull/1905

at some point we can make the styling app-wide and redesign metadraw, the task windows, etc. it's kind of a lot of work because a lot of the current xaml is copied+pasted code blocks and i'm trying to move away from that towards defining styles once and then referencing that style elsewhere.

**Comment by rmillikin** [comment]
i'm looking forward to the v a p o r w a v e metamorpheus theme
