### ISSUE TITLE
Few question re- O-glyco pair

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1917]
Hi Guys,

Awesome feature! I have a few question i didn't found the answer for the glycosites file:
1. can you write somewhere the abbv. for the glycans? couldn't fins what is A.
2. what's the difference between the localisation levels?
3. can you explain the numbers in "All potential glycan localizations" and "AllSiteSpecificLocalizationProbability"

thanks!
D.

**Comment by trishorts** [comment]
Nice to get some feedback. We think this is working really well. We have a preprint that should answer most questions. https://www.biorxiv.org/content/10.1101/2020.05.18.102327v1

Of course we're happy to receive early feedback as it's still out for review at a journal and we have time to make updates.

**Comment by Dmorgen** [comment]
This IS working very well, and you’ve set-up the viewer very well for that (oh, how I wish it could do all the mods this way…)!
Can you say what’s the difference between the grey and yellow annotations on the sequence in metadraw?

D.

**Comment by Dmorgen** [comment]
well - if we're already talking about that...
1. the setup of the annotated sequences in MetaDraw is a bit weird for me, the top sequence belongs to the bottom spectra while the bottom sequence is for the top spectra. is it supposed to be like that?
2. is it possible to run both N & O glycans? I've had multiple proteins with both on the same peptide.
3. how would stepped HCD affect the search? I'm using stepped for some of the N-glycans as they give better fragmentation than EThcD.
4. can you annotate the Y-ions on the peptide fragments? I've noticed several "ladders" that were not annotated.

Thanks!
D.

**Comment by trishorts** [comment]
I sent a message to the guy from our group that is the primary contributor. he will answer your technical questions.

We have tried to make it so you can do a combination of of different fragmentation modes to get the best out of it. I think we might be the only group doing that. Lei can speak directly to that question.

Combination N/O will be here shortly. But, we could probably get you a pre-release if you have interest. It's not ready for prime time but moving fast.

We'll get you an answer on the Y-ions.

**Comment by Dmorgen** [comment]
Awesome! Of course I’m interested ☺

**Comment by lonelu** [comment]
Hi D,
Thanks for trying O-Pair. Your feedbacks are very important to us.

1. Name	Symbol
	Hex	H
	HexNAc	N
	NeuAc	A
	NeuGc	G
	Fuc	F
	Phospho	P
	Sulfo	S
	Na	Y
	Ac	C
	Xylose	X
	SuccinylHex	U
	Formylation	M
	
2. You may already find explanation of localization level in the preprint.
3. All potential glycan localizations: for unlocalized O-Glycans, show all potential the glycan on potential glycosites.
	AllSiteSpecificLocalizationProbability: provide the site probability for every possible site. 
	Those are mainly for level 2 and level 3 ids. For example: 
	Peptide Base Sequence:	STNASTVPFRNPDENSR 
	GlycanLocalizationLevel:	Level2	
	Localized Glycans with Peptide Site Specific Probability:	[6,H1N1,0.994]	
	Localized Glycans with Protein Site Specific Probability:	[223,H1N1,0.994]	
	All potential glycan localizations:	{@10[2-1,6-1]}{@10[1-1,6-1]}
		{@10[2-1,6-1]}	corresponding to {GlycanGroupId 10, [Glycosite 2, glycanId 1], [Glycosite 6, glycanId 1]}
	AllSiteSpecificLocalizationProbability:{@1[1,0.500]}{@2[1,0.500]}{@5[1,0.006]}{@6[1,0.994]}{@16[1,0.000]}
		{@1[1,0.500]} corresponding to {Site 1, [glycanId 1, probability 0.5]}
	
	For this peptide there are two H1N1 modified. We report H1N1 on S6 which could be localized with probability 0.994, the other glycan could be at either S1 or T2 based on the probabiliy and thus it is a leval 2 id.   

~ Gray means not-localized. Yellow means localized.

1. MetaDraw is not specialily designed for the purpose so it looks weird. You are right about the sequence positions. We will see how to make it better.

2. The preprint is specially for O-glyco search. The N-Glyco search in MM 0.0.308 is not very mature.
	If your sample contains both N- and O-glycans. You may want to try our a pre-release which can search N- O- at the same time as Shortreed mentioned. Otherwise it is possible to mis identify a N-Glycopeptide as a O-Glycopeptide. The pre-release also have better N-glyco search.
	
3.	Again I don't suggesting search N-Glycan using the version 0.0.308. 
	Stepped-HCD or any other type of fragmentation methods are surely supported for Glyco Search in the new development. 
	
4.	Y-ions are annotated as ('M-0.000' mins a mass). The reason you 'noticed several "ladders" that were not annotated' is due to that the current method may loss matching a few Y ions due to Y ions containing multiple charge state and possible deconvolution problem. We are working on this and thanks for pointing this out. We want to know more about this if possible. 

Thanks for your interest in trying our pre-release. I upload it https://uwmadison.box.com/s/ifuuy3nag8o4ill4qmx8u29pm123f9zw as "netcoreapp3.1_MM0530.zip" . 

Let me know if you have other questions. We really appreciate your effect helping us improving MM.

Lei

**Comment by trishorts** [comment]
Lei, can you add all this to the wiki if its not there. That's good stuff!

**Comment by Dmorgen** [comment]
Thanks for the detailed answer!

D.
