### ISSUE TITLE
MetaDraw not finding psmtsv from MetamorpheusXL

### ISSUE THREAD

**Issue by Rodolpho7** [smith-chem-wisc/MetaMorpheus#1960]
Hello everyone,
I have generated XL datasets with Metamorpheus XL.
I would like to annotate those link using MetaDraw on my Mass Spectrum.

However I am unable to find the .psmtsv files that MetaDraw requires. Are those the intra/interlinks.tsv files of my dataset?
How can I input that in on Metadraw?

I am using the GUI version.
Best

**Comment by rmillikin** [comment]
Hi Rodolpho,

I answered via email but I'll include my response here for completeness.

There are currently 2 bugs that require workarounds that will be fixed in the next MetaMorpheus release.

1. The XL results .tsv files can be added to MetaDraw via drag-and-drop. Currently pressing the "Select" button in the interface will not list .tsv as a valid file format, so drag-and-drop is the required workaround
2. The file name in the XL .tsv file lists the full file path of the data file (e.g., C:\MyData\MyDataFile.raw). Replace this field with the data file name without extension (e.g., MyDataFile instead of C:\MyData\MyDataFile.raw).

These bugs are fixed in #1959 and will be included in the next release. Thanks for the bug report!
