### ISSUE TITLE
How to pass experimental design on the MM linux version

### ISSUE THREAD

**Issue by javanOkendo** [smith-chem-wisc/MetaMorpheus#1972]
I have an experimental design file and I am not sure how to pass this in the commandline version of the tool. I have tried to look for this from the help but it is not captured. Could you share the full command for passing the experimental design using the commandline version?

**Comment by rmillikin** [comment]
If you have the ExperimentalDesign.tsv in the folder with your spectra files, it will get read in automatically, though currently there is a bug where it will only get read in if normalization is enabled. The experimental design is mostly only used for normalization though at the moment, though it does also affect MBR a bit, and the order in which intensities are reported in the proteins and peptides files. This issue is fixed in #1970 .

Also, in that same PR, I've added a message "Read ExperimentalDesign.tsv successfully" that displays if the experimental design was read in, so it's a little less ambiguous if the experimental design was used or not.

**Comment by javanOkendo** [comment]
@rmillikin thanks I tried it and it worked
