### ISSUE TITLE
XL scoring question

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1999]
Hi,

which of the values would you use as a cutoff measure? Qval_PEP? PEP? Qval?

Thanks!
David.

**Comment by lonelu** [comment]
Please use QValue. The PEP and QVal PEP are still under development.

**Comment by Dmorgen** [comment]
Thanks!

**Comment by talpa25** [comment]
Dear developers,

question with same regard. I do compare my CrosslinkDataSet output of Metamorpheus with the output of pLink and XlinkX. If the QValue is equal to the FDR confidence with 0.01 = 1% than the QValue is not sufficient, because MetaMorpheus gives me only a handful of positives (1-5). When I have a look at the PEP_QValue, the data output looks quite comparable to the ones of pLink and XlinkX, but I have some decoys in it. 
Just by the way, what is the definition of PEP and PEP_QValue? Like the FDR on the peptide level?
How do you calculate the FDR/confidence score of the crosslinks?

Best regards and merry christmas!

Roman

**Comment by lonelu** [comment]
Hi Roman,
PEP is short for Posterior Error Probability. It is a probability trained by Binary Tree with several psm features. So PEP is still at psm level. The idea is similar to Percolator. My advisor Shortreed knows more about it. We will have a paper soon to show how it works. 
You can use the PEP_QValue as QValue. Just filter PEP_QValue <= 0.01, and remove all Decoys. 
I also observe the situation you described. I need to have a discussion with Shortreed about if we want to use PEP_QValue instead of QValue.
Thanks for your feedback and comment. Feel free to contact us.
Lei Lu

Lei
