### ISSUE TITLE
Number of Peptides in Experiment with multiple conditions

### ISSUE THREAD

**Issue by MKoesters** [smith-chem-wisc/MetaMorpheus#2008]
Hi all,

In the proteingroups output file is a column called `Number of Peptides`. If analysing multiple conditions, does this include the peptides across all conditions?
If so, is there an easy way to get the number of peptides for a given protein per condtion?

Best,
Manuel

**Comment by trishorts** [comment]
It is across all conditions. I'll ask Rob if the peptides/condition is a feature of FlashLFQ and let you know.

**Comment by MKoesters** [comment]
I'd also have another question regarding this table.
Are the protein intensities the summed up intensities of all peptides/psms?
Or are only a fraction of peptides considered, e.g. peptides with a q-value or PEP below a certain cutoff?

I'm analysing a SILAC experiment and I'm having some issues with way more light than heavy peptides quantified and I'm afraid this will skew the protein ratios, if the number of quantified peptides for a given protein vary greatly between the two conditions

**Comment by trishorts** [comment]
are you using the SILAC functionality of metamorpheus or are you doing quant some other way. our student zach has done lots of work on the SILAC.

**Comment by zrolfs** [comment]
Hi @MKoesters ,
MetaMorpheus only quantifies peptides if they were identified at a 1% FDR (q-value < 0.01). These peptide intensities are then used to determine protein intensities. I believe the top 3 most intense heavy-light peptide pairs (averaged across all replicates) are used for each protein. @rmillikin can correct me if it's using something other than top 3.

MetaMorpheus does some cool things where it tries to find each heavy-light pair. If you only identify the heavy or light (but not both), it will try to find the complementary peak so that both peaks are quantified. You can also use match-between-runs to reduce variability between replicates.

Let me know if you have any other questions!
Zach

**Comment by MKoesters** [comment]
Perfect, thats the information I was looking for!
In case I have further questions I'll come back to you.
I'd would also be nice to have information like this in the docs.
Is it already somewhere and I missed it or are there plans to add this?

Best,
Manuel
