### ISSUE TITLE
requesting a new enzyme

### ISSUE THREAD

**Issue by fazeliniah** [smith-chem-wisc/MetaMorpheus#2041]
Dear MetaMorpheus developers. 
We are using a new enzyme for our bottom-up proteomics: 
https://www.sciencedirect.com/science/article/pii/S1535947620600172
ProAlanase cuts at the c-terminus of Ala and Pro. How is the best way to add a new enzyme to the database in MetaMorpheus?
Thanks

**Comment by mjfitzhenry** [comment]
Yes, I would also like this enzyme added as an option in MM please

**Comment by acesnik** [comment]
Hi there,

Adding a new protease isn't a feature in MetaMorpheus, yet, but you can try adding a new protease manually by going to the `ProteolyticDigestion\proteases.tsv` file and adding a row for a new protease:
![image](https://user-images.githubusercontent.com/16342951/113829855-468d2880-9786-11eb-9b36-f05d5da577f8.png)
![image](https://user-images.githubusercontent.com/16342951/113829994-70dee600-9786-11eb-9732-c5717c753097.png)

It's not an ideal method, since there is no error checking for the additional entries (MetaMorpheus won't open if something is wrong), but it's something you could try.

**Comment by acesnik** [comment]
You can probably just copy-paste the `Glu-C (with asp)` line and change the name to ProAlanase and the sequences inducing cleavage to alanine and proline instead of aspartic and glutamic acid.

**Comment by mjfitzhenry** [comment]
Seems to work fine. It didn't throw up any errors. Thanks mate.

**Comment by acesnik** [comment]
Cool, no problem!

I'd recommend checking out the Previous and Next Amino Acid columns in the PSM results file (below is for a trypsin run) for a sanity check to make sure the results make sense.
![image](https://user-images.githubusercontent.com/16342951/113854123-cc1cd280-979e-11eb-8fe6-a883810691a0.png)

-AC
