### ISSUE TITLE
Setting up a nonspecific search without GUI

### ISSUE THREAD

**Issue by MKoesters** [smith-chem-wisc/MetaMorpheus#2082]
Hi all,

I'm trying to do a non-specific search and configure the toml by hand, since I don't have access to a windows machine.
Since the wiki has only tutorial for the GUI version, I'm using these as an Orientation.
However I'm not sure how to change to the Non-specific search mod.

changing `SearchModeType = "Full"` to `SearchModeType="Non-specifc"` does not work, however I found out that `SearchModeType = "Semi"` would work.
What is the right argument I need to use?

Also, are there some example tomls for a non-specific search which I could adapt (I'm planning to do a calibration, search and quantification using FlashLFQ) 

Best,
Manuel

**Comment by MKoesters** [comment]
Found out that the correct line would be

`SearchModeType = None`

**Comment by zrolfs** [comment]
Hi Manuel,
Thanks for reaching out. We've been leaning into the GUI for a while and we certainly need to add more command line documentation for non-windows users. Until that happens, I've attached a few example tomls for calibration and search/quant and given you some notes. If you have any more questions, we'll get back to you ASAP.

Notes: 
IMPORTANT: I changed the extension on these files from "toml" to "txt" because Github won't let me upload files with weird extensions. Just change the extensions back to "toml" before you use them

Maybe Important: The parameter "MaxMissedCleavages" should always be equal to "MaxPeptideLength" - 1.  If not, you might get some unexpected results.

Calibration: Non-specific calibration is typically super slow, so we typically calibrate on a subset of data. I sent you a calibration toml I use for HLA-I peptides. These peptides are overwhelmingly 9 amino acids long, so it saves time to only calibrate on 9-mers rather than search for peptides with 7-25 amino acids. 

Search: There are two search modes for doing non-specific searches. The first is the traditional method, "SlowNonSpecific_SearchAndQuant", which is generally slow because the search time scales with the number of allowed peptide lengths.  If you're only looking for 9-mer peptides, this method will be pretty fast. If you're looking for peptides with lengths of 7-25, then use "SpeedyNonSpecific_SearchAndQuant". This method uses a [neat trick](https://www.eurekaselect.com/181499/article) to search all peptides simultaneously. 

[SpeedyNonSpecific_SearchAndQuant.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/6808367/SpeedyNonSpecific_SearchAndQuant.txt)
[CalibrateTask-HLA1.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/6808368/CalibrateTask-HLA1.txt)
[SlowNonSpecific_SearchAndQuant.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/6808369/SlowNonSpecific_SearchAndQuant.txt)
.

**Comment by MKoesters** [comment]
Thank you for the fast reply, thats exactly what I was looking for.
Out of curiosity, could you point me to the part of the code, where the parameters are parsed and validated?
This would make it easiert for me next time I'm trying to find valida parameter values

Best,
Manuel

**Comment by zrolfs** [comment]
For sure. 
We use a nuget package called "Nett" to read/write toml files. This package cleverly reads/writes all the properties of an object. Although clever, it's not super transparent.

An example of reading a search toml is found in [Program.cs](https://github.com/smith-chem-wisc/MetaMorpheus/blob/774eddb8c98600ce9619d813c1bb0845410c4902/CMD/Program.cs), line 209

When that line is called, Nett creates a new SearchTask object ([SearchTask.cs](https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/TaskLayer/SearchTask/SearchTask.cs))
which has properties of CommonParameters and SearchParameters. You can look at the file for [CommonParameters.cs](https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/EngineLayer/CommonParameters.cs) and [SearchParameters.cs](https://github.com/smith-chem-wisc/MetaMorpheus/blob/master/TaskLayer/SearchTask/SearchParameters.cs).

This is quite a few layers, but lets say you were interested in figuring out what the SearchModeType parameter should be (as per your original question). This parameter is located under the line "CommonParameters.DigestionParams", so we know the property is stored in [DigestionParams.cs ](https://github.com/smith-chem-wisc/mzLib/blob/master/Proteomics/ProteolyticDigestion/DigestionParams.cs). You're then looking for "SearchModeType" (located on line 39) to find out it's a "CleavageSpecificity" object type.  If you then go to [CleavageSpecificity.cs](https://github.com/smith-chem-wisc/mzLib/blob/6103cb8ee23d19074f81ffc6c3f559362bff56bd/Proteomics/ProteolyticDigestion/CleavageSpecificity.cs), you'll see all the possible options for this parameter.

That's pretty complicated, but we've found it to be an effective way for to handle long term stability/maintenance in the program.
