### ISSUE TITLE
Recursive RAW file addition

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#210]
Low-priority feature request: 

The original Morpheus allowed drag-and-drop of a folder into the Data Files grid, and it would populate it with all of the RAW files or otherwise in the file tree below that folder. This would be a nice feature to add back into MetaMorpheus, as long as it doesn't present problems for other reasons.

**Comment by stefanks** [comment]
Also, could run combined analyses hierarchically: say have main folder, with subfolders corresponding to bioreps, and these have subfolders corresponding to technical replicates. Analysis should then be run for each aggregate level, instead of the current case where it is only run for all files individually, and one analysis for all files together.

**Comment by stefanks** [comment]
This would actually make some recent experiments I ran much simpler, and would only necessitate a single metamorpheus instance instead of many. 
Could also then show the raw files in a tree instead of a list.

**Comment by trishorts** [comment]
Currently can't drop folders containing raw files into MM. I'd like to see this feature.

**Comment by acesnik** [comment]
I've implemented this in ProteoformSuite. See ProteoformSuiteInternal -> Lollipop -> enter_input_files() if you want.

**Comment by stefanks** [comment]
Drop folders and recursive addition is working. Moved the hierarchical analysis to a new issue: https://github.com/smith-chem-wisc/MetaMorpheus/issues/291
