### ISSUE TITLE
File was not found in the dictionary

### ISSUE THREAD

**Issue by AmirWIS** [smith-chem-wisc/MetaMorpheus#2100]
I get an error, noting that the run has failed, with the error that one of the files was not found in the dictionary. 
I re-ran only that file, and it was okay. 
What does that error means?

**Comment by acesnik** [comment]
I'm not sure. If you see the error again, could you please paste the full error message or a screenshot into the issue here? 

Otherwise, I believe there is an option to report the error to the metamorpheus email. Did you click that button to send the error report?

Which files is it complaining about? Please share an example of the files that reproduce the error.

Thanks!

**Comment by acesnik** [comment]
Thank you for reporting the issue. Please reopen another if you encounter it again.
