### ISSUE TITLE
Modification fragment mass additions depending on fragmentation method

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#216]
ETD, CID etc fragment differently and the "FM" field should be expanded to consider how the modification behaves under different fragmentation conditions (labile, etc)

**Comment by stefanks** [comment]
Yes. This should be an issue on mzLib, since that is where the modification reading is happening.
There should be three options:

1. No "FM" field at all. Mass attached to individual fragments is always assumed to equal "MM" (monoisotopic mass)
2. "FM" field as is: For example "FM   0" means that modification is assumed to always be labile, or "FM   0 16" means modification assumed to leave either no mass or a 16 dalton mass on peptide fragmentation, regardless of fragmentation type
3. A custom format for "FM" field, that specifies what happens to the modification when peptide is fragmented, depending on the type of fragmentation. 

Rob, do you have a specific suggestion for 3?

**Comment by trishorts** [comment]
see #1264
