### ISSUE TITLE
Proteins in different samples types with the exact intensity values. 

### ISSUE THREAD

**Issue by AmirWIS** [smith-chem-wisc/MetaMorpheus#2163]
Processing data from three co-IP different sample types, using MetaMorpheus v0.0.320, and searched against the Mouse proteome database (Mouse_SP_Jan2022), we noticed that some of the identified proteins (in the proteinGroups output) had the exact normalized value. Most of those proteins were identified and quantified by at least 4 unique peptides. Each peptide had different intensity value in the different samples, but performing the calculation manually (by using the peptides output, and normalizing to the TIC), I found that the values are similar but not identical as in the proteinGroups output. 
It looks very strange to me as it is hard to believe that in about 10 cases (from ~360 protein identifications), the proteins had the exact same value between the different sample types. 
Please check the attached proteins and peptides file, and as an example, take the protein with the accession ID of Q60597. This protein had 6 unique peptides
[Peptides-report.xlsx](https://github.com/smith-chem-wisc/MetaMorpheus/files/9189197/Peptides-report.xlsx)
[Proteins-Report.xlsx](https://github.com/smith-chem-wisc/MetaMorpheus/files/9189198/Proteins-Report.xlsx)

**Comment by trishorts** [comment]
thanks for the comment. we have seen this. I was thinking that it was fixed. but perhaps there haven't been some updates passed through to this release of metamorpheus

**Comment by trishorts** [comment]
I think this bug is fixed here: https://github.com/smith-chem-wisc/mzLib/pull/624

that is in a nuget package that metamorpheus uses. So, i think we need to update the nuget in metamorpheus and make a new release. That is challenging at the moment because of issues out of our control. There is currently no support for our installer wix in vs2022 and no support for .net 6 in vs2019. we are in never never land. I don't want to update metamorpheus and cause problems for all of our users. I may be able to get you a pre-release to try. please watch this space over the next couple days.

**Comment by trishorts** [comment]
fixed in the next relase
