### ISSUE TITLE
PEP calculations use target count in denominator

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#225]
instead of total (target + decoy)

**Comment by stefanks** [comment]
What do you mean by PEP calculations? We output q-value which we compute by decoy/(target + decoy). This corresponds to false discovery rate. Do you want to completely change this?

**Comment by stefanks** [comment]
Targets already contain false positives, so dividing by that gives decoy/(true positives + false positives). This might be a better estimate.

**Comment by zrolfs** [comment]
I agree that decoy/target is a correct calculation of FDR for us, since the number of targets include both the false- and true-positives. With our current q=decoy/(target+decoy), you can never have more than a 50% FDR, even if all of the identifications are incorrect, which is fallacious.
The current error is negligible at 1% FDR where targets>>decoys, but at lower confidence such as 10% FDR, it is important to calculate q as decoy/target.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/pull/692
