### ISSUE TITLE
output GPTMD database w/ only novel PTMS  confirmed @ 1% FDR

### ISSUE THREAD

**Issue by lschaffer2** [smith-chem-wisc/MetaMorpheus#246]
Instead of a GPTMD database with all potential modifications added, a database with only novel ones added that made it past the 2nd search w/ 1% FDR (for ProteoformSuite)
(If it already does this, close this issue)

**Comment by stefanks** [comment]
Doesn't do this yet. It should be an option for the Search task

**Comment by stefanks** [comment]
The cleanest way is to write a database with only modifications identified in the search. This would remove the original uniprot modifications! This is easy to implement. We could try this first, and if you feel that the uniprot mods should be there even if not identified by MM, we could do something different.

Looking back at the previous task results to see what was added is hacky... Since the tasks are all independent of each other. This might necessitate another column with checkboxes in the modification list, that stands for "write to new database only if observed in 1% FDR PSM results".

**Comment by lschaffer2** [comment]
For ProteoformSuite I definitely do think all mods annotated in uniprot should be included. These could be observed by intact but not BU especially due to sequence coverage. I'm only concerned about adding novel PTMs to the database that weren't actually observed by bottom up with 1% FDR especially when analyzing labelfree data. 

Could you maybe combine the original database with the database w/ only modifications identified, just making sure not to repeat the overlap between the two when writing it?

**Comment by stefanks** [comment]
Alright! It will be done, but not by combining the original database, but rather by selectively pruning the gptmd database. 

This is a programming decision, since this pruned database writing would be done in a search task that would take a full gptmd database in as an input.

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/MetaMorpheus/commit/4c65aa8ee1ba7930281d1b39bbf50f291e9ec9ae
