### ISSUE TITLE
Button to cancel processing without crashing MM

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#302]
I frequently find that I want to change some setting and restart a search. Now. I have to crash MM and then reload everything. Be nice to just stop processing and be able to amend search paramters. Then start over.

**Comment by acesnik** [comment]
I put 15 mins into this while waiting to get coffee earlier. Just aborting the EverythingEngine thread doesn't work. The CPU was still working hard. What other tasks need to be shut down?

**Comment by stefanks** [comment]
All the parallel for loops it seems!

https://msdn.microsoft.com/en-us/library/dd460721%28v=vs.110%29.aspx

**Comment by acesnik** [comment]
It turns out this is pretty tough. I tried to propagate aborting the thread that hosts the EverythingRunnerEngine through all of the Parallel.For loops, but this isn't a great solution, since you need to sense the change to the containing thread from within the parallel loop. There's also this [CancelationToken structure](http://stackoverflow.com/questions/6052699/how-can-i-kill-all-threads-spawned-by-parallel-foreach-from-my-main-thread) that I haven't tried, but it also depends on testing within the loop. It seems like the Parallel loops should have a list of the threads spawned, perhaps one with the active threads, or at least some way of accessing that information, but that doesn't exist. 

We might be able to achieve halting these processes efficiently if we do the thread managing ourselves instead of relying on the System.Threading.Tasks.

**Comment by acesnik** [comment]
My changes are here: https://github.com/smith-chem-wisc/MetaMorpheus/pull/304, but I'm planning to abandon this issue for now.

**Comment by acesnik** [comment]
Thanks to whomever removed the nested Parallel.For/Each loops, I was able to implement this fairly easily. It'll be in my next pull request.

**Comment by zrolfs** [comment]
Neat! Can you have a window that pops up to make sure the user didn't accidentally click it?

**Comment by acesnik** [comment]
Sure, good thought!

**Comment by rmillikin** [comment]
done in #1280
