### ISSUE TITLE
Add a note in GptmdTaskWindow for where to find "write pruned db" (search window)

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/MetaMorpheus#397]

**Comment by zrolfs** [comment]
This is a pretty old issue and the GUI's changed a bit since this was opened. Pruned databases are currently output in the search task (not the gptmd task). The output location is the same folder location as the rest of the output, so it's intuitive that it would be written there and a note shouldn't really be needed, especially when our group is the only one using this function.

**Comment by rmillikin** [comment]
I think the intent of this issue is that if the user wants to run GPTMD and then trim the output, there is no obvious text saying "hey, go over to the search task and make a pruned database." The issue is just to put a note in the GPTMD task to head over to the search task if you want a pruned DB.

**Comment by zrolfs** [comment]
I'm still not sure where that note would appear in the window, especially since it's such a niche thing that will be confusing to most users and require an explanation of what a pruned database is. It seems to me that the wiki would be a better place to put this information.

**Comment by zrolfs** [comment]
Or, perhaps, the proteoformsuite wiki.

**Comment by rmillikin** [comment]
We should probably get together and talk about where/what to say with this message (or just chat about it on slack). Most users don't need it and may be confused by its meaning.
