### ISSUE TITLE
Remove hard coded 3 variable modification limit

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#495]
And make it a user choice

**Comment by lonelu** [comment]
There is other hard coded variables. Since every Task have some common parameters like max missed cleavages, protease..... Adding a hard coded 3 variable modification limit is easy but need to change a lot places in MM. Is that a good idea to create a 'Common Parameter Class' contains all common parameter as 'Properties {get; set;}' to make things easier in the future?

**Comment by stefanks** [comment]
Something like this is a great idea!

There are a few further sub-categories of these parameters that are shared between all tasks:

- Search parameters
- In-silico digestion parameters
- Raw file loading parameters
- Performance/memory parameters

It would make the super long RunSpecific calls be short and sweet. 

Then every task has some task-specific parameters

**Comment by zrolfs** [comment]
Is this available now? Can it be closed?

**Comment by stefanks** [comment]
Yes
