### ISSUE TITLE
Suggested Tolerances are buggy

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#518]
We tend to search calibrated files at 5ppm/0.01 Da, but not all calibrated files are equal. Could there be an output (maybe appended to the new filename?) that includes at what tolerance 99% of the 1% FDR PSMs fell within at the last pass? This would aid in future searches that use the calibrated file as well as acting as a sort of diagnostic tool for assessing the quality of the spectra.

**Comment by zrolfs** [comment]
This is now provided in the calib.toml files, correct?

**Comment by stefanks** [comment]
Yup. Needs more testing though.

**Comment by stefanks** [comment]
Still a bug in the output, here is a plot of suggested precursor mass tolerances for each of the 28 calibrated Jurkat fractions. 3 of them are clear outliers. 

![image](https://user-images.githubusercontent.com/5972770/33615091-cf26a3e6-d99e-11e7-8b0d-2647973cfe7b.png)

**Comment by rmillikin** [comment]
see also #949

**Comment by rmillikin** [comment]
decided to nix the suggested tolerances until proven not buggy. #1044

**Comment by rmillikin** [comment]
suggested tolerances are more consistent in #1059 . I'm testing to see if the suggested tolerances generally improve on default tolerances next.
![suggestedtolerances](https://user-images.githubusercontent.com/24705713/38141741-35df59c4-33ff-11e8-8339-8bc25dde5723.png)

**Comment by rmillikin** [comment]
Looks like number of PSMs and peptides increase across the board in this dataset using suggested tolerances instead of the default. I'm sure there are files when this is not true; the suggested tolerances are not guaranteed to be optimal or better than the default ones. But for now, we can be fairly confident that the suggested tolerances work well in most? many? cases.

![suggestedtolpsmimprovement](https://user-images.githubusercontent.com/24705713/38149073-bf90cc42-341e-11e8-92ba-f3650aec90f7.png)

(the results were kind of annoying to sort by fraction number so the x-axis is arbitrary in this one)

**Comment by zrolfs** [comment]
Awesome work Rob! Can you post calibrated files + tomls on bison?
