### ISSUE TITLE
Automatic paragraph output for papers

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#62]

**Comment by acesnik** [comment]
Cool idea, effectively turning the params.txt file into draft prose.

**Comment by trishorts** [comment]
Protein Search Databases. Protein FASTA and XML files were obtained from the UniProt repository(25). Protein accession numbers (14,138 entries for Jurkat and 43,238 entries for mouse) included in the databases are supplied in supplemental Table S1, and the summarized list of target PTM types from the XML file is in supplemental Table S2. The database used for the Jurkat samples was the Homo sapiens (Human) reference proteome from UniProt release 2013_12 (downloaded December 23, 2013). The database used for the mouse samples was the Mus musculus (Mouse) reference proteome from UniProt release 2013_12 (downloaded December 23, 2013), supplemented with the list of common contaminants available at the following URL: ftp://ftp.thegpm.org/fasta/cRAP 
Database Searching. The software program Morpheus (version 75b) was used for all database searching. It can be obtained at http://morpheus-ms.sourceforge.net/. For this work, it was modified to accept UniProt XML in addition to FASTA protein databases. When a UniProt XML database is specified, all curated modifications are extracted. Details of each modification (name, mass shift, target) are read from a local copy of http://www.uniprot.org/docs/ptmlist. All valid modifications are added to the variable modifications box in the Morpheus graphical user interface with the prefix “UniProt:” and selected by default. During each search, all protein sequences are read along with the locations of selected UniProt variable modifications. The order of the unmodified and modified amino acid residues is reversed during on-the-fly generation of decoy protein sequences. Post-translational modifications move with their companion amino acid. For example, the phosphorylated tetrapeptide, TES(UniProt: Phosphoserine)Q, becomes QS(UniProt: Phosphoserine)ET..
A critical routine in the code takes a base peptide sequence and generates all of the isoform combinations possible given the variable modifications selected, up to a user-defined limit (1024 by default). This code was modified slightly to consider UniProt modifications only at their location as reported in the database. Otherwise the logic for combinatorially generating all possible peptide isoforms is identical.
Searches were performed on a Dell Precision T3500 desktop computer with a Xeon 3.20 GHz processor and 24.0 GB of RAM using 4 cores. The following settings were used in all searches: Protease = trypsin (no proline rule); Maximum Missed Cleavages =2; Initiator Methionine Behavior =variable; Fixed Modifications = carbamidomethylation of C; Variable Modifications = oxidation of M; Maximum Variable Modification Isoforms Per Peptide = 1024; Precursor Mass Tolerance = ±2.1 Da (monoisotopic); Precursor Monoisotopic Peak Correction = disabled; Product Mass Tolerance = ±0.01 Da (monoisotopic); Maximum False Discovery Rate = 1%. FASTA vP searches used additionally variable phosphorylation of S, T and Y. G-PTM searches used XML database files rather than FASTA files. Counts of post-translationally modified peptides do not include the oxidation of methionine or the carbamidiomethylation of cysteine as these occur during sample handling and therefore are somewhat uninteresting. Peptide search results for human and mouse are provided in supplemental Tables S3-S8 and the corresponding protein identifications are provided in supplemental Tables S9-S14. Summary lists of identified proteins including numbers of PSMs (total and modified) are provided in supplemental Table S15 for both Jurkat and mouse, where B6 and CAST mouse data are segregated to allow for their comparison. Total search times are as follows: Jurkat FASTA – 123 min.; Jurkat G-PTM – 136 min.; Jurkat variable phosphorylation – 1402 min.; mouse FASTA – 148 min.; mouse G-PTM – 168 min.; mouse variable phosphorylation – 1666 min.;

**Comment by trishorts** [comment]
The above text could be modified appropriately for the auto text. It came from an MCP manuscript submission that didn't make it.

**Comment by stefanks** [comment]
Done
