### ISSUE TITLE
Add "Artefact" type of mod classification

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#624]
would aid in distinguishing PTMs from artefacts. So mods like formylation are both PTM and artefact depending on their location. Carbamylation is an artefact, not a PTM.

**Comment by stefanks** [comment]
See this: https://github.com/smith-chem-wisc/MetaMorpheus/issues/319

What exactly is "artefact"? We need precise defintions for the different modification types. Should keep this in mind: https://github.com/smith-chem-wisc/MetaMorpheus/issues/631 so that modifications can easily be split by whether they would be useful for proteoform suite or not.

**Comment by rmillikin** [comment]
is the current implementation of this enough? the "essential sequence" and the options to not write certain mods for the pruned DB?

**Comment by trishorts** [comment]
this modification type now exists and is populated. pruned database selection does not write this mods (unless selected) and essential sequence contains other observed PTMs (uniprot/biological) set for writing to pruned db. the list needs to evolve but the functionality is correct. I'm closing this issue.
