### ISSUE TITLE
Modern search may miss correct matches if product tolerance does not fully overlap bin

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#713]
A match may be considered to be superior if the fragments match bins, but those same fragments may not be accepted by the product mass tolerance.

**Comment by rmillikin** [comment]
My somewhat-complicated solution to this is a three-tiered scoring system (right now it's two-tiered). Each tier gets more computationally expensive.

1) Static-bin-width scoring (currently in Modern Search); +1 for each peptide contained in the millidalton-rounded fragment bin. Very fast and filters out most garbage but can result in some false-positive fragment matches. Note that this score can never be lower than the actual number of matched fragments, but it can potentially be higher.
2) Refined fragment-tolerance scoring (new addition); everything that meets the minimum-score requirement (e.g., 5) is re-scored (still an integer, representing number of matched ions) but using the real fragment ppm tolerances to filter out any false-positive fragment matches. Probably only slightly more expensive than 1) and you're only doing it for a relatively few peptides that pass the score threshold. But too expensive to do as an initial score for every fragment match.
3) Final scoring (currently in Modern Search); every peptide match with the highest score (e.g., 23) is re-scored using the expensive CalculatePeptideScore, to resolve some ambiguity, add intensity to the score, etc.

**Comment by stefanks** [comment]
Rob, it sounds like a good plan, but it's still a heuristic, so I would say that we should have a very good reason to implement it. For example, real improvement in ids at a cost of  a tiny increase in search time.

Some info we need before any coding is done: what are the fragment ppm accuracies for the various bottom up and top down files we have, from various instruments, calibrated and uncalibrated? How common is having different fragment masses in the same bin? What are the practical limitations on the bin width for computers with various RAM? How is the search speed/results affected by various choices of bin width? What is the variable bin width idea?

**Comment by rmillikin** [comment]
fixed in #1138. It's technically slower but it's basically the same speed unless you're doing an open-mass search coupled with 1) a very low score cutoff or 2) are calculating e-values.

A first-pass scoring is done as described above with a static bin width of 1 mDa. The "real" score cannot be higher than the first-pass score, only lower. 

Every peptide that passes the first-pass scoring is re-scored with the "real" scoring function (MetaMorpheusEngine.CalculatePeptideScore) to filter out false-positives. Previously only peptides with the same first-pass score as the peptide with the highest first-pass score would be re-scored; now _all_ of the peptides that meet the first-pass score cutoff are re-scored.

Let me know if you notice an unacceptable performance hit...

**Comment by zrolfs** [comment]
Clever solution. I like that only a small subset of peptides making it past the score cutoff "filter" are saved for more accurate scoring. This could be an efficient way to implement more computationally intensive scoring methods in the future. I am concerned about the impact it will have on Neo (complementary ions and weighted ions dramatically increase the number of theoreticals scoring above 5), but we can cross that bridge when I "re-merge" Neo.
