### ISSUE TITLE
Installer crash on choosing repair option 

### ISSUE THREAD

**Issue by stefanks** [smith-chem-wisc/MetaMorpheus#802]
![error](https://user-images.githubusercontent.com/5972770/33347213-be0f5cde-d457-11e7-9985-189846ba74a8.png)

**Comment by XRSHEERAN** [comment]
Should be a problem due to package/product codes. Here are one similar [problem](https://stackoverflow.com/questions/18086314/error-1334-from-installer) and a [reference](https://blogs.msdn.microsoft.com/pusu/2009/06/10/what-are-upgrade-product-and-package-codes-used-for/) for these codes. Needs more details to determine the bug!

**Comment by stefanks** [comment]
I believe this happened when I already had MM installed, and I opened the installer of the same version. And tried the repair option.

**Comment by XRSHEERAN** [comment]
Fixed! Added auto-generated guid to package and no problem occurs when I have the same version installed.
