### ISSUE TITLE
Search-Task not starting after Calibration-Task

### ISSUE THREAD

**Issue by VotanWarnwitz** [smith-chem-wisc/MetaMorpheus#944]
Hi,
when I try to search my data using the calibration and search task I recieve the followong warning message after completion of the calibration task:

currentResult.Ms1List.Count = 0 currentResult.Ms2List.Count = 0
datapointAcquisitionResult is null
Cannot proceed. No data files selected.

The search Task will not be started afterwards. The Output directory and the analyzed raw-file can be downloaded via:
https://www.dropbox.com/sh/i4e8hg4ndxu1rql/AADCtxAzuZz1xXL3GSd_1qt-a?dl=0

The MetaMorpheus version used was 0.0.260.0
As far as I understood the calibration task should output a mzML file but I can't see/find it anywhere :/

Any help would be appreciated. 
Thank you

Best,
Franz

**Comment by rmillikin** [comment]
Hi Franz,

We're still investigating the Calibration Task issue, but from our tests it seems that running the Search Task with a 100ppm product tolerance gives much better results (5000 PSMs) than searching with the default 20ppm product tolerance (400 PSMs).  MetaMorpheus is generally intended for high-res MS1 and MS2 but it may still work with low-res MS2. I'm not seeing resolution info in the scan header of the MS2 scans, but is it indeed low-res MS2 data? I think for now, you will need to skip the Calibration Task (it's optional - you can go directly to the Search Task), but we will get back to you on this issue.

Rob

**Comment by VotanWarnwitz** [comment]
Hi Rob,
thank you for the info! MS2 spectra are indeed low res (ITMS + c). During calibration Task much more peptides are identified in comparison to solely performing the search task. That is why I was hoping to combine the calibration with the search task. Can calibration of the MS2 scans be an optional feature? In the end I would like to run overall 64 raw files with MetaMorpheus and would like to use the MatchBetweenRuns feature as well. MSI calibration would therefor be great (and probably enough for my needs :D)
Thanks!

Best,
Franz

**Comment by stefanks** [comment]
Hi Franz,

There are a few things happening regarding this issue:

- The error you got originally happened due to you having selected a product tolerance that is too restrictrive (25 ppm). This will be fixed in an upcoming release, by giving the user a suggestion of tuning their tolerances. For this file, Param-Medic recommends at least 100ppm, and I would use around 400 ppm product tolerance. 
- Even with using better initial tolerances, calibrating your files in release 0.0.260 still fails due to an unrelated issue, regarding empty scans with no peaks. This will be fixed in an upcoming release.
- Calibration helps a little, by centering ms1 ppm errors around zero, see histogram below. MS2 errors also improve by a tiny amount, but searching even the uncalibrated file can be sufficient. 
![hist](https://user-images.githubusercontent.com/5972770/36268496-3ce08cbe-123c-11e8-8997-70a2bd7ff3a3.png)
- What do you mean by "much more peptides are identified in comparison to solely performing the search task"?
- You assigned Deamidations as variable modifications. We do not recommend using any modifications other than Oxidation of M as variable, since they significantly slow down searches. Instead, try to use a G-PTM-D task prior to using a search task, with selecting a few common modifications in G-PTM-D. A search with an augmented database is fast and gives significantly more PSMs. By selecting these modifications in G-PTM-D "Mod\tDeamidation on N\t\tMod\tDeamidation on Q\t\tMod\tAmmonia loss\t\tMod\tPhospho on S\t\tPeptideTermMod\tAmmonia loss on Q\t\tPeptideTermMod\tAcetald+26", I am able to get around 6000 PSMs, instead of 5000 PSMs using the orginal databases

**Comment by stefanks** [comment]
Oh and there is no need to uncheck Carbamidomethyl of U! Selenoprotein P with accession P49908 seems to be present in your sample, and scan 2299 seems to match  AEENITESC[Common   Fixed:Carbamidomethyl of C]QU[Common Fixed:Carbamidomethyl of U]R

More evidence for this protein is in scans 32398 32352 which match to peptide LVYHLGLPFSFLTFPYVEEAIK only present in that protein

**Comment by VotanWarnwitz** [comment]
@stefanks: Thank you for all the advice and the information and for looking into this issue and my data in such detail. I will run my files with your recommended settings :D 
I will check out Param-Medic asap as well! 

To answer your question: 
"What do you mean by "much more peptides are identified in comparison to solely performing the search task"?" - Due to the less stringent parameters there are obviously more PSMs and (I would expect) more peptides identified in the sample file. This is of course obvious but slipped my mind somehow yesterday evening. (I am still a rookie in the field of mass spectrometry :/ -  this is the reason why I also missed the product tolerance completly despite my MS2 data being low res (thank you again stefanks and Rob for pointing that out).   

"You assigned Deamidations as variable modifications." - This is typical in my lab...deamidations seems to happen a lot during in solution digestions. My colleagues are normally using it during Mascot searches. Deamidation seems to be less of an issue in more acidic milieu using these low pH protein digestion kits. I don't know about FASP digestion - haven't tried this yet.

Once again: Thank you for your help and the continuing development of this sweet piece of software!
Keep up the great work! :D 

Best,
Franz

**Comment by trishorts** [comment]
One point that Stefan was trying to make was that it is best practice to perform the G-PTM-D task, which has deamidation as one of the modifications. Then use that database in a search task, with only oxidized methionine as the variable mod. With G-PTM-D, you will see all the deamidations that you expect but you won't pay the same penalty in false discovery rate that you do when you use deamidation as a variable mod. As an experiment, I suggest that you take your data and run the standard G-PTM-D task with adjusted peak tolerances of (10ppm parent and 400ppm fragment). Then run the standard search task with those same tolerances and don't add deamidation. I think that you'll see several PSMs from deamidation.

**Comment by VotanWarnwitz** [comment]
@trishorts: thank you for clarifying this. I might have another question regarding the G-PTM-D editing of the database but I better check out the publication again first before asking stupid questions ;)

**Comment by trishorts** [comment]
don't hesitate to ask. I'm master of the stupid question. Ask anyone that sees me daily. Also, good for others to read the answers. I guess many people will have similar questions.

**Comment by VotanWarnwitz** [comment]
@trishorts 
Thanks! Will do so for sure :D

**Comment by rmillikin** [comment]
This should be fixed in 0.0.262, please give it a try!
